kind: pipeline
name: default

steps:
  - name: build
    image: node:10
    commands:
      - npm ci
      - npm run build
    when:
      branch:
        - master

  - name: deploy-ftp
    image: signalwerk/lftp:latest
    commands:
      - bash ./ci/lftp.sh push
    environment:
      FTP_SERVER: berufssc.myhostpoint.ch
      FTP_USER: signalwerk@sfgz.ch
      FTP_PASSWORD:
        from_secret: "FTP_PASSWORD"
      FTP_LOCAL_DIR: .
      FTP_REMOTE_DIR: /www/sfgz.ch/main/Packages/Sites/signalwerk.sfgz/
    when:
      branch:
        - master

  - name: build-cache
    image: pstauffer/curl:latest
    commands:
      - curl -s -I https://sfgz.ch
    when:
      branch:
        - master
