Neos:
  Flow:
    i18n:
      defaultLocale: 'de_CH.utf8'
  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: 'smtp.office365.com'
        port: '587'
        encryption: 'tls'
        authMode: 'LOGIN'
        username: 'weiterbildung@sfgz.ch'
        password: "%env:MAIL_PASSWORD%"
        localDomain: 'sfgz.ch'
        sourceIp: '34.65.45.216'
